name: Build wasm binaries

on:
  push:
    branches: [main, wasm-dev]

jobs:
  build-wasm:
    name: wasm-pack build
    runs-on: ubuntu-latest
    env:
      ACCESS_HEADER: user:${{ secrets.GH_ACTIONS_PAT }}@
    steps:
      #- uses: actions-rs/toolchain@v1
      #  with:
      #    toolchain: nightly
      #    override: true
      #    profile: minimal

      - uses: actions/checkout@v1
      - run: |
          git config --global user.name "PopcornPaws"
          git config --global user.email "mark@gold.xyz"
          bash build-wasm.sh
        #cargo install wasm-pack
