name: Build wasm binaries

on:
  push:
    branches: [main, wasm-dev]

jobs:
  build-wasm:
    name: wasm-pack build
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
      USERNAME: PopcornPaws
      WASM_HUB_REPO: agora-wasm-hub
      WASM_HUB_BRANCH: ${{ github.repository }}@${{ github.ref_name }}
      WASM_DIR: tom256
      WASM_OUT: wasm-output
    steps:
      #- uses: actions-rs/toolchain@v1
      #  with:
      #    toolchain: nightly
      #    override: true
      #    profile: minimal

      - uses: actions/checkout@v1
      - run: |
          git config --global user.name $USERNAME
          git config --global user.email "mark@gold.xyz"
          mkdir ${WASM_DIR}/${WASM_OUT} # remove this
          cd ${WASM_DIR}/${WASM_OUT}
          git init # remove this
          touch hello.rs # remove this
          rm -f .gitignore
          git remote add origin https://x-access-token:"$ACCESS_TOKEN"@github.com/agoraxyz/"$WASM_HUB_REPO"
          git branch -M $WASM_HUB_BRANCH
          git add -A
          git commit -m "Auto-generated wasm binaries"
          git push -uf origin $WASM_HUB_BRANCH
        #cargo install wasm-pack
        #wasm-pack build $WASM_DIR --target bundler --out-name index --out-dir $WASM_OUT
